name: Docker

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  push:
    branches:
      - main
      - dev

jobs:
  construir_y_publicar:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout del código
      uses: actions/checkout@v2

    - name: Login en Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Construir y etiquetar la imagen Docker
      run: |
        if [ ${{ github.ref }} = 'refs/heads/main' ]; then
          docker build -t usuario/nombre-de-la-imagen:stable .
          docker push usuario/nombre-de-la-imagen:stable
        elif [ ${{ github.ref }} = 'refs/heads/dev' ]; then
          docker build -t usuario/nombre-de-la-imagen:latest .
          docker push usuario/nombre-de-la-imagen:latest
        fi
